---
- hosts: server1
  tasks:
    - name: "Create users"
      include_tasks: create.yml
      loop:
        - username: jane
          has_readme: yes
        - username: jim
          has_readme: no
        - username: jill
          has_readme: yes
