---
- name: Host a website with Apache2
  hosts: Server1
  become: yes
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Optional: this line makes the cache valid for an hour, preventing unnecessary updates

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Copy custom greeting page to Apache document root
      ansible.builtin.copy:
        src: /Users/oliver/Desktop/ansible/greeting.txt
        dest: /var/www/html/index.html
